# ----------------------- base -----------------
FROM node:lts-alpine AS base

USER root
# Update image
RUN apk update && apk upgrade --available && apk add --no-cache g++ make python3

COPY . /app
WORKDIR /app

# Add NX
RUN yarn global add nx@latest 

# ----------------------- dependencies -----------------
FROM base AS deps

RUN npm install --only=development

# ------------------------ builder ---------------
FROM base AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

RUN yarn generate2
RUN yarn build:be

# ------------------------ runner ---------------------
FROM node:lts-alpine AS runner

WORKDIR /app

COPY --from=builder /app/dist/packages/be-gateway ./
COPY ./packages/shared-models/src/prisma/schema.prisma .
COPY ./yarn.lock .

RUN yarn install

COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma

# Set both HOST and PORT explicitly
ENV HOST=0.0.0.0
ENV PORT=3000

# Use a shell to start the app with explicit host and port
CMD node main.js
