app = 'namviek'
primary_region = 'sin'

[build]
  dockerfile = 'docker/backend/Dockerfile-flyio'

[env]
  JWT_REFRESH_EXPIRED = '2d'
  JWT_TOKEN_EXPIRED = '30m'
  JWT_VERIFY_USER_LINK_TOKEN_EXPIRED = '10m'
  HOST = '0.0.0.0'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[scale]
  count = 1
  max = 1

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
