app = "namviek"  # replace with your app name
primary_region = "sin"  # replace with your preferred region, e.g., sin for Singapore

[env]
JWT_VERIFY_USER_LINK_TOKEN_EXPIRED = "10m"
JWT_SECRET_KEY = "09123skjdhfwe"
JWT_TOKEN_EXPIRED = "30m"
JWT_REFRESH_KEY = "Iw98erhsd"
JWT_REFRESH_EXPIRED = "2d"
PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
