// app/layout.tsx
import './global.css';
import './style/index.css'
import { Inter } from 'next/font/google';
import RootLayoutComp from '../layouts/RootLayout';
import { GoalieProvider } from '@goalie/nextjs';
import Head from 'next/head';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <GoalieProvider>
      <html lang="en">
        <head>
          <title>Kampuni</title>
        </head>
        <body className={inter.className}>
          <RootLayoutComp>{children}</RootLayoutComp>
        </body>
      </html>
    </GoalieProvider>
  );
}
