// app/layout.tsx
import './global.css'
import './darkmode.css'
import './style/index.css'
import { Inter } from 'next/font/google'
import RootLayoutComp from '../layouts/RootLayout'
import { GoalieProvider } from '@goalie/nextjs'
import Head from 'next/head'

import dynamic from 'next/dynamic'
const inter = Inter({ subsets: ['latin'] })

const PushNotification = dynamic(
  () => import('./_components/PushNotification'),
  { ssr: false }
)

export const metadata = {
  title: 'Taffyo',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <GoalieProvider>
      <html lang="en">
        <head>
          <title>Taffyo</title>
        </head>
        <body className={inter.className}>
          <RootLayoutComp>{children}</RootLayoutComp>
          <PushNotification />
        </body>
      </html>
    </GoalieProvider>
  )
}
