name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy to ${{ matrix.region }}
    runs-on: ubuntu-latest
    concurrency: deploy-group
    strategy:
      matrix:
        include:
          - region: Singapore
            app: namviek-sin
          - region: Virginia
            app: namviek-vir
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to ${{ matrix.region }}
        run: flyctl deploy --remote-only --app ${{ matrix.app }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

